before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs firefox-esr
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --path /cache
  - bundle exec rake db:create RAILS_ENV=test

rspec:
  script:
    - bundle exec rspec
